
	<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sidebar-collapse"><span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span></button>
				<a class="navbar-brand" href="#"><span>Walailak</span>Alerts</a>
				<ul class="nav navbar-top-links navbar-right">
					<li class="dropdown"><a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
						<em class="fa fa-bell"></em><span class="label label-danger">15</span>
					</a>
						<ul class="dropdown-menu dropdown-messages">
							<li>
								<div class="dropdown-messages-box"><a href="profile.html" class="pull-left">
									<img alt="image" class="img-circle" src="http://placehold.it/40/30a5ff/fff">
									</a>
									<div class="message-body"><small class="pull-right">3 mins ago</small>
										<a href="#"><strong>ผศ.เยาวเรศ</strong> ประกาศงดคลาส </a>
									<br /><small class="text-muted">1:24 pm - 25/03/2015</small></div>
								</div>
							</li>
							
							<li class="divider"></li>
							<li>
								<div class="all-button"><a href="#">
									<em class="fa fa-inbox"></em> <strong>ข่าวประกาศทั้งหมด</strong>
								</a></div>
							</li>
						</ul>
					</li>
					
				</ul>
			</div>
		</div><!-- /.container-fluid -->
	</nav>
	<div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">
		<div class="profile-sidebar">
			<div class="profile-userpic">
				<img src="http://placehold.it/50/30a5ff/fff" class="img-responsive" alt="">
			</div>
			<div class="profile-usertitle">
				<div class="profile-usertitle-name">พุธธิดา</div>
				<div class="profile-usertitle-status"><span class="indicator label-success"></span>Online</div>
			</div>
			<div class="clear"></div>
		</div>
		<div class="divider"></div>
		
		<ul class="nav menu">
			<li class="active"><a href="index.html"><em class="fa fa-dashboard">&nbsp;</em> หน้าแรก</a></li>
			<li><a href="login.html"><em class="fa fa-power-off">&nbsp;</em> ลงชื่อออก</a></li>
		</ul>
	</div><!--/.sidebar-->
		
	<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
		<div class="row">
			<ol class="breadcrumb">
				<li><a href="#">
					<em class="fa fa-home"></em>
				</a></li>
				<li class="active">หน้าแรก</li>
			</ol>
		</div><!--/.row-->
		
		<div class="row">
			<div class="col-lg-12">
				<h1 class="page-header">หน้าแรก</h1>
			</div>
		</div><!--/.row-->
		
			
		<div class="panel panel-default ">
					
						
					<div class="panel-body timeline-container">
						<ul class="timeline">
							<li>
									<div class="timeline-panel">
									<div class="timeline-heading">
										<h4 class="timeline-title">ประกาศงดคลาส</h4>
									</div>
									<div class="timeline-body">
                                        <p>ประกาศงดคลาส SWE-333 เนื่องจากมีค่ายกิจกรรม 4 ชั้นปี จะประกาศวันสอนชดเชยภายหลัง</p>
                                        <div class="input-group">
							            <input id="btn-input" type="text" class="form-control input-md" placeholder="แสดงความคิดเห็น"><span class="input-group-btn">
								        <button class="btn btn-primary btn-md" id="btn-todo">โพสต์</button>
						            </span></div>
									</div>
								</div>
							</li>
							
						</ul>
					</div>
				</div>
			</div>	

