
	<div class="row">
		<div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-4 col-md-offset-4">
			<div class="login-panel panel panel-default">
				<div class="panel-heading">Log in</div>
				<div class="panel-body">
					<?php
            	echo $this->tag->form(
              [
                "auth/signin",
                "autocomplete" => "off",
                "id" => "signin-form"
              ]
            );
            ?>
						<fieldset>
							<input type="hidden" name="<?php echo $this->security->getTokenKey() ?>"
            value="<?php echo $this->security->getToken() ?>"/>
							<div class="form-group">
								<input class="form-control" placeholder="E-mail" name="id"  autofocus="">
							</div>
							<div class="form-group">
								<input class="form-control" placeholder="Password" name="password" type="password" value="">
							</div>
							<div class="checkbox">
								<label>
									<input name="remember" type="checkbox" value="Remember Me">Remember Me
								</label>
							</div>
							<button class="btn btn-primary">Login</button>
						</fieldset>
					<?php echo $this->tag->endForm(); ?>
				</div>
			</div>
		</div><!-- /.col-->
	</div><!-- /.row -->	
	


