<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sidebar-collapse"><span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span></button>
            <a class="navbar-brand" href="#"><span>Walailak</span>Alerts</a>
            <ul class="nav navbar-top-links navbar-right">
                
                        
                    <ul class="dropdown-menu dropdown-alerts">
                        <li><a href="#">
                            <div><em class="fa fa-envelope"></em> 1 New Message
                                <span class="pull-right text-muted small">3 mins ago</span></div>
                        </a></li>
                        <li class="divider"></li>
                        <li><a href="#">
                            <div><em class="fa fa-heart"></em> 12 New Likes
                                <span class="pull-right text-muted small">4 mins ago</span></div>
                        </a></li>
                        <li class="divider"></li>
                        <li><a href="#">
                            <div><em class="fa fa-user"></em> 5 New Followers
                                <span class="pull-right text-muted small">4 mins ago</span></div>
                        </a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div><!-- /.container-fluid -->
</nav>
<div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">
    <div class="profile-sidebar">
        <div class="profile-userpic">
            <img src="http://placehold.it/50/30a5ff/fff" class="img-responsive" alt="">
        </div>
        <div class="profile-usertitle">
            <div class="profile-usertitle-name">ผศ.เยาวเรศ</div>
            <div class="profile-usertitle-status"><span class="indicator label-success"></span>Online</div>
        </div>
        <div class="clear"></div>
    </div>
    <div class="divider"></div>
        <ul class="nav menu">
        <li class="active"><a href="index.phtml"><em class="fa fa-dashboard">&nbsp;</em> หน้าแรก</a></li>
        <li><a href="insertNews.phtml"><em class="fa fa-clone">&nbsp;</em>เพิ่มข่าวประกาศ</a></li>
        <li><a href="/login/login"><em class="fa fa-power-off">&nbsp;</em> ลงชื่อออก</a></li>
    </ul>
</div><!--/.sidebar-->
    
<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
    <div class="row">
        <ol class="breadcrumb">
            <li><a href="#">
                <em class="fa fa-home"></em>
            </a></li>
            <li class="active">หน้าแรก</li>
        </ol>
    </div><!--/.row-->
    
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">หน้าแรก</h1>
        </div>
    </div><!--/.row-->
    
				<div class="panel panel-default ">
					
						
					<div class="panel-body timeline-container">
						<ul class="timeline">
							<li>
									<div class="timeline-panel">
									<div class="timeline-heading">
										<h4 class="timeline-title">ประกาศงดคลาส</h4>
									</div>
									<div class="timeline-body">
                                        <p>ประกาศงดคลาส SWE-333 เนื่องจากมีค่ายกิจกรรม 4 ชั้นปี จะประกาศวันสอนชดเชยภายหลัง</p>
                                        <div class="input-group">
							            <input id="btn-input" type="text" class="form-control input-md" placeholder="แสดงความคิดเห็น"><span class="input-group-btn">
								        <button class="btn btn-primary btn-md" id="btn-todo">โพสต์</button>
						            </span></div>
									</div>
								</div>
							</li>
							
						</ul>
					</div>
				</div>
			</div>